import { Component, ViewEncapsulation } from '@angular/core';
import {BootstrapIconComponent, BootstrapIconsRegistry,} from '@triangular/bootstrap-icons';

import {
  bootstrapIconAlarmFill,
  bootstrapIconAlarm,
  bootstrapIconAlt,
  bootstrapIconAppIndicator,
  bootstrapIconApp,
  bootstrapIconArchiveFill,
  bootstrapIconArchive,
  bootstrapIconArrow90DegDown,
  bootstrapIconArrow90DegLeft,
  bootstrapIconArrow90DegRight,
  bootstrapIconArrow90DegUp,
  bootstrapIconArrowBarDown,
  bootstrapIconArrowBarLeft,
  bootstrapIconArrowBarRight,
  bootstrapIconArrowBarUp,
  bootstrapIconArrowClockwise,
  bootstrapIconArrowCounterclockwise,
  bootstrapIconArrowDownLeft,
  bootstrapIconArrowDownRight,
  bootstrapIconArrowDownShort,
  bootstrapIconArrowDown,
  bootstrapIconArrowLeftRight,
  bootstrapIconArrowLeftShort,
  bootstrapIconArrowLeft,
  bootstrapIconArrowRepeat,
  bootstrapIconArrowReturnLeft,
  bootstrapIconArrowReturnRight,
  bootstrapIconArrowRightShort,
  bootstrapIconArrowRight,
  bootstrapIconArrowUpLeft,
  bootstrapIconArrowUpRight,
  bootstrapIconArrowUpShort,
  bootstrapIconArrowUp,
  bootstrapIconArrowsAngleContract,
  bootstrapIconArrowsAngleExpand,
  bootstrapIconArrowsCollapse,
  bootstrapIconArrowsExpand,
  bootstrapIconArrowsFullscreen,
  bootstrapIconArrowsMove,
  bootstrapIconAspectRatioFill,
  bootstrapIconAspectRatio,
  bootstrapIconAt,
  bootstrapIconAwardFill,
  bootstrapIconAward,
} from '@triangular/bootstrap-icons/icons';
import {NgForOf} from "@angular/common";

@Component({
  selector: 'app-icons-a',
  templateUrl: './icons-a.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  imports: [
    BootstrapIconComponent,
    NgForOf
  ],
  standalone: true
})
export class IconsAComponent {
  icons = [
    bootstrapIconAlarmFill,
    bootstrapIconAlarm,
    bootstrapIconAlt,
    bootstrapIconAppIndicator,
    bootstrapIconApp,
    bootstrapIconArchiveFill,
    bootstrapIconArchive,
    bootstrapIconArrow90DegDown,
    bootstrapIconArrow90DegLeft,
    bootstrapIconArrow90DegRight,
    bootstrapIconArrow90DegUp,
    bootstrapIconArrowBarDown,
    bootstrapIconArrowBarLeft,
    bootstrapIconArrowBarRight,
    bootstrapIconArrowBarUp,
    bootstrapIconArrowClockwise,
    bootstrapIconArrowCounterclockwise,
    bootstrapIconArrowDownLeft,
    bootstrapIconArrowDownRight,
    bootstrapIconArrowDownShort,
    bootstrapIconArrowDown,
    bootstrapIconArrowLeftRight,
    bootstrapIconArrowLeftShort,
    bootstrapIconArrowLeft,
    bootstrapIconArrowRepeat,
    bootstrapIconArrowReturnLeft,
    bootstrapIconArrowReturnRight,
    bootstrapIconArrowRightShort,
    bootstrapIconArrowRight,
    bootstrapIconArrowUpLeft,
    bootstrapIconArrowUpRight,
    bootstrapIconArrowUpShort,
    bootstrapIconArrowUp,
    bootstrapIconArrowsAngleContract,
    bootstrapIconArrowsAngleExpand,
    bootstrapIconArrowsCollapse,
    bootstrapIconArrowsExpand,
    bootstrapIconArrowsFullscreen,
    bootstrapIconArrowsMove,
    bootstrapIconAspectRatioFill,
    bootstrapIconAspectRatio,
    bootstrapIconAt,
    bootstrapIconAwardFill,
    bootstrapIconAward,
  ];

  constructor(private registry: BootstrapIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
