import { Component, ViewEncapsulation, inject } from '@angular/core';
import { BootstrapIconsRegistry, } from '@triangular/bootstrap-icons';

import {
  bootstrapIconBackspaceFill,
  bootstrapIconBackspaceReverseFill,
  bootstrapIconBackspaceReverse,
  bootstrapIconBackspace,
  bootstrapIconBagFill,
  bootstrapIconBag,
  bootstrapIconBarChartFill,
  bootstrapIconBarChart,
  bootstrapIconBatteryCharging,
  bootstrapIconBatteryFull,
  bootstrapIconBatteryHalf,
  bootstrapIconBattery,
  bootstrapIconBellFill,
  bootstrapIconBell,
  bootstrapIconBlockquoteLeft,
  bootstrapIconBlockquoteRight,
  bootstrapIconBookHalf,
  bootstrapIconBook,
  bootstrapIconBookmarkCheck,
  bootstrapIconBookmarkDash,
  bootstrapIconBookmarkFill,
  bootstrapIconBookmarkPlus,
  bootstrapIconBookmark,
  bootstrapIconBookmarksFill,
  bootstrapIconBookmarks,
  bootstrapIconBootstrapFill,
  bootstrapIconBootstrapReboot,
  bootstrapIconBootstrap,
  bootstrapIconBoundingBoxCircles,
  bootstrapIconBoundingBox,
  bootstrapIconBoxArrowDownLeft,
  bootstrapIconBoxArrowDownRight,
  bootstrapIconBoxArrowDown,
  bootstrapIconBoxArrowInDownLeft,
  bootstrapIconBoxArrowInDownRight,
  bootstrapIconBoxArrowInDown,
  bootstrapIconBoxArrowInLeft,
  bootstrapIconBoxArrowInRight,
  bootstrapIconBoxArrowInUpLeft,
  bootstrapIconBoxArrowInUpRight,
  bootstrapIconBoxArrowInUp,
  bootstrapIconBoxArrowLeft,
  bootstrapIconBoxArrowRight,
  bootstrapIconBoxArrowUpLeft,
  bootstrapIconBoxArrowUpRight,
  bootstrapIconBoxArrowUp,
  bootstrapIconBraces,
  bootstrapIconBriefcaseFill,
  bootstrapIconBriefcase,
  bootstrapIconBrightnessAltHighFill,
  bootstrapIconBrightnessAltHigh,
  bootstrapIconBrightnessAltLowFill,
  bootstrapIconBrightnessAltLow,
  bootstrapIconBrightnessHighFill,
  bootstrapIconBrightnessHigh,
  bootstrapIconBrightnessLowFill,
  bootstrapIconBrightnessLow,
  bootstrapIconBrush,
  bootstrapIconBucketFill,
  bootstrapIconBucket,
  bootstrapIconBuilding,
  bootstrapIconBullseye,
} from '@triangular/bootstrap-icons/icons';

@Component({
  selector: 'app-icons-b',
  templateUrl: './icons-b.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  standalone: false // eslint-disable-line @angular-eslint/prefer-standalone
})
export class IconsBComponent {
  private registry = inject(BootstrapIconsRegistry);

  icons = [
    bootstrapIconBackspaceFill,
    bootstrapIconBackspaceReverseFill,
    bootstrapIconBackspaceReverse,
    bootstrapIconBackspace,
    bootstrapIconBagFill,
    bootstrapIconBag,
    bootstrapIconBarChartFill,
    bootstrapIconBarChart,
    bootstrapIconBatteryCharging,
    bootstrapIconBatteryFull,
    bootstrapIconBatteryHalf,
    bootstrapIconBattery,
    bootstrapIconBellFill,
    bootstrapIconBell,
    bootstrapIconBlockquoteLeft,
    bootstrapIconBlockquoteRight,
    bootstrapIconBookHalf,
    bootstrapIconBook,
    bootstrapIconBookmarkCheck,
    bootstrapIconBookmarkDash,
    bootstrapIconBookmarkFill,
    bootstrapIconBookmarkPlus,
    bootstrapIconBookmark,
    bootstrapIconBookmarksFill,
    bootstrapIconBookmarks,
    bootstrapIconBootstrapFill,
    bootstrapIconBootstrapReboot,
    bootstrapIconBootstrap,
    bootstrapIconBoundingBoxCircles,
    bootstrapIconBoundingBox,
    bootstrapIconBoxArrowDownLeft,
    bootstrapIconBoxArrowDownRight,
    bootstrapIconBoxArrowDown,
    bootstrapIconBoxArrowInDownLeft,
    bootstrapIconBoxArrowInDownRight,
    bootstrapIconBoxArrowInDown,
    bootstrapIconBoxArrowInLeft,
    bootstrapIconBoxArrowInRight,
    bootstrapIconBoxArrowInUpLeft,
    bootstrapIconBoxArrowInUpRight,
    bootstrapIconBoxArrowInUp,
    bootstrapIconBoxArrowLeft,
    bootstrapIconBoxArrowRight,
    bootstrapIconBoxArrowUpLeft,
    bootstrapIconBoxArrowUpRight,
    bootstrapIconBoxArrowUp,
    bootstrapIconBraces,
    bootstrapIconBriefcaseFill,
    bootstrapIconBriefcase,
    bootstrapIconBrightnessAltHighFill,
    bootstrapIconBrightnessAltHigh,
    bootstrapIconBrightnessAltLowFill,
    bootstrapIconBrightnessAltLow,
    bootstrapIconBrightnessHighFill,
    bootstrapIconBrightnessHigh,
    bootstrapIconBrightnessLowFill,
    bootstrapIconBrightnessLow,
    bootstrapIconBrush,
    bootstrapIconBucketFill,
    bootstrapIconBucket,
    bootstrapIconBuilding,
    bootstrapIconBullseye,
  ];

  constructor() {
    const registry = this.registry;

    registry.registerIcons(this.icons);
  }

}
