import { Component, ViewEncapsulation, inject } from '@angular/core';
import { BootstrapIconsRegistry, } from '@triangular/bootstrap-icons';

import {
  bootstrapIconFileArrowDown,
  bootstrapIconFileArrowUp,
  bootstrapIconFileBreak,
  bootstrapIconFileCheck,
  bootstrapIconFileCode,
  bootstrapIconFileDiff,
  bootstrapIconFileEarmarkArrowDown,
  bootstrapIconFileEarmarkArrowUp,
  bootstrapIconFileEarmarkBreak,
  bootstrapIconFileEarmarkCheck,
  bootstrapIconFileEarmarkCode,
  bootstrapIconFileEarmarkDiff,
  bootstrapIconFileEarmarkMinus,
  bootstrapIconFileEarmarkPlus,
  bootstrapIconFileEarmarkRuled,
  bootstrapIconFileEarmarkSpreadsheet,
  bootstrapIconFileEarmarkText,
  bootstrapIconFileEarmarkZip,
  bootstrapIconFileEarmark,
  bootstrapIconFileMinus,
  bootstrapIconFilePlus,
  bootstrapIconFilePost,
  bootstrapIconFileRichtext,
  bootstrapIconFileRuled,
  bootstrapIconFileSpreadsheet,
  bootstrapIconFileText,
  bootstrapIconFileZip,
  bootstrapIconFile,
  bootstrapIconFilesAlt,
  bootstrapIconFiles,
  bootstrapIconFilm,
  bootstrapIconFilterLeft,
  bootstrapIconFilterRight,
  bootstrapIconFilter,
  bootstrapIconFlagFill,
  bootstrapIconFlag,
  bootstrapIconFolderCheck,
  bootstrapIconFolderFill,
  bootstrapIconFolderMinus,
  bootstrapIconFolderPlus,
  bootstrapIconFolderSymlinkFill,
  bootstrapIconFolderSymlink,
  bootstrapIconFolder,
  bootstrapIconFonts,
  bootstrapIconForwardFill,
  bootstrapIconForward,
  bootstrapIconFullscreenExit,
  bootstrapIconFullscreen,
  bootstrapIconFunnelFill,
  bootstrapIconFunnel,
} from '@triangular/bootstrap-icons/icons';

@Component({
  selector: 'app-icons-f',
  templateUrl: './icons-f.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  standalone: false // eslint-disable-line @angular-eslint/prefer-standalone
})
export class IconsFComponent {
  private registry = inject(BootstrapIconsRegistry);

  icons = [
    bootstrapIconFileArrowDown,
    bootstrapIconFileArrowUp,
    bootstrapIconFileBreak,
    bootstrapIconFileCheck,
    bootstrapIconFileCode,
    bootstrapIconFileDiff,
    bootstrapIconFileEarmarkArrowDown,
    bootstrapIconFileEarmarkArrowUp,
    bootstrapIconFileEarmarkBreak,
    bootstrapIconFileEarmarkCheck,
    bootstrapIconFileEarmarkCode,
    bootstrapIconFileEarmarkDiff,
    bootstrapIconFileEarmarkMinus,
    bootstrapIconFileEarmarkPlus,
    bootstrapIconFileEarmarkRuled,
    bootstrapIconFileEarmarkSpreadsheet,
    bootstrapIconFileEarmarkText,
    bootstrapIconFileEarmarkZip,
    bootstrapIconFileEarmark,
    bootstrapIconFileMinus,
    bootstrapIconFilePlus,
    bootstrapIconFilePost,
    bootstrapIconFileRichtext,
    bootstrapIconFileRuled,
    bootstrapIconFileSpreadsheet,
    bootstrapIconFileText,
    bootstrapIconFileZip,
    bootstrapIconFile,
    bootstrapIconFilesAlt,
    bootstrapIconFiles,
    bootstrapIconFilm,
    bootstrapIconFilterLeft,
    bootstrapIconFilterRight,
    bootstrapIconFilter,
    bootstrapIconFlagFill,
    bootstrapIconFlag,
    bootstrapIconFolderCheck,
    bootstrapIconFolderFill,
    bootstrapIconFolderMinus,
    bootstrapIconFolderPlus,
    bootstrapIconFolderSymlinkFill,
    bootstrapIconFolderSymlink,
    bootstrapIconFolder,
    bootstrapIconFonts,
    bootstrapIconForwardFill,
    bootstrapIconForward,
    bootstrapIconFullscreenExit,
    bootstrapIconFullscreen,
    bootstrapIconFunnelFill,
    bootstrapIconFunnel,
  ];

  constructor() {
    const registry = this.registry;

    registry.registerIcons(this.icons);
  }

}
